### ISSUE TITLE
Performance: Unresponsive "List all tabs" with high tab count

### ISSUE THREAD

**Issue by Cooldude2606** [Godiesc/firefox-gx#246]
A month ago some changes where introduced which increased the unresponsiveness of "List all tabs" with a high tab count. My tab list contains about 1100 tabs. Before these changes it would open in two or three seconds which was acceptable for such a large number of tabs. However after the change it can take upwards of 30 seconds making it unusable. I have narrowed it down to the following code snippets:

`ogx_contextual-menu.css` lines 41 to 43.
```css
:root:not(:has(#context-ask-chat[hidden="true"])) #frame-sep {
    display: flex !important;
}
```

`ogx_oneline.css` lines 265 to 270.
```css
:root:not([chromehidden~="toolbar"]):has(#PersonalToolbar[collapsed="true"]),
:root:not([chromehidden~="toolbar"]):has(#sidebar-main[hidden="true"],sidebar-main[hidden]){
  :is(#nav-bar,#toolbar-menubar) {
    margin-inline-start: 0px !important;
  }
}
```

I do not know enough css to even start exploring why these are causing increased unresponsiveness in the tab list. But I do know that when I comment these blocks out it returns to the old bahviour of only taking two or three seconds. If either one is present then it causes performance issues, if both are present the effect is compounded.

Could this performance issue be investigated and alternative solutions be explored for the issues fixed by these snippets. If there is anything you would like me to provide then I am happy to provide most things.

**Comment by Godiesc** [comment]
Hi, the first code keeps the separator visible in the page contextual menu when you have enabled the Chatbot IA, to fix a rare animation.

The second code Just reset the margin of menubar and navbar, I don't know how that could affect the 'list-all-tabs' button, I don't manage a lot of tabs, but I will try to test it to see the problem.

Are you sure the theme is causing this issue, or could be a Firefox update problem?

**Comment by Godiesc** [comment]
Seems like the problem appears when you enable the left-sidebar or the Firefox sidebar-revamp.
The online style isn't the problem. I will check what could be causing this performance issue in the sidebar styles.
Thanks for the report, I hope to find a solution.

**Comment by yuuqilin** [comment]
The `:root:has()` and `:root:not(:has())` selectors can be computationally expensive. Using variables to pass values can help avoid this issue. For example, instead of writing:

```css
:root:has(foo) bar { margin-inline-start: 0px !important; }
```

You can rewrite it as:

```css
:root:has(foo) { --toolbar-margin-inline-start: 0px; }
bar { margin-inline-start: var(--toolbar-margin-inline-start) !important; }
``` 

This approach improves performance by reducing the need for complex selector checks.

**Comment by Cooldude2606** [comment]
Thanks for looking into this so quickly, my Firefox version is 136.0 and im using the latest release on this repo which is also 136. I am using oneline theme and I do not have left sidebar enabled. (I don't know what the revamp is, but I assume that is also not enabled because I am not using the sidebar)

Using the suggestion from @yuuqilin I have changed the code snippets to the following:

```css
:root:not(:has(#context-ask-chat[hidden="true"])) { --context-ask-chat-display: flex }
#frame-sep { display: var(--context-ask-chat-display) !important; }
```

```css
:root:not([chromehidden~="toolbar"]):has(#PersonalToolbar[collapsed="true"]) { --toolbar-margin-inline-start: 0px }
:root:not([chromehidden~="toolbar"]):has(#sidebar-main[hidden="true"], sidebar-main[hidden]) { --toolbar-margin-inline-start: 0px }
#nav-bar, #toolbar-menubar { margin-inline-start: var(--toolbar-margin-inline-start) !important; }
```

The performance is now the same as when it was commented out. But I am not skilled enough to know if this covers the edge cases the snippets were introduced to fix. If you could validate that these work the same as the orginals then this would be a fix for this performance issue.
